name: 'Prettier'
description: 'This action runs Prettier.'
inputs:
  github_token:
    description: 'The Github API token needed for Checks action.'
  working_directory:
    description: Where is your package.json and therefore your node_modules located.
    required: false
    default: ''
  prettier_args:
    description: 'Where should Prettier look?'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:

    - name: Prettier
      id: prettier
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        if \
        prettier_result="$(node_modules/.bin/prettier \
        --no-error-on-unmatched-pattern \
        --check ${{ inputs.prettier_args }} 2>&1 > /dev/null)"; \
        then \
        echo "::set-output name=prettier_status::success"; \
        echo "::set-output name=prettier_summary::Everything looks good!"; \
        echo "::set-output name=prettier_text_description::Nothing to complain about."; \
        else \
        echo "::set-output name=prettier_status::failure"; \
        echo "::set-output name=prettier_summary::Forgot to run Prettier?"; \
        echo "::set-output name=prettier_text_description::$(echo $prettier_result)"; \
        fi;

    - uses: LouisBrunner/checks-action@v1.1.1
      with:
        token: ${{ inputs.github_token }}
        name: prettier
        conclusion: ${{ steps.prettier.outputs.prettier_status }}
        output: |
          {"summary":"${{ steps.prettier.outputs.prettier_summary }}", "text_description":"${{ steps.prettier.outputs.prettier_text_description }}"}

branding:
  icon: 'terminal'
  color: 'gray-dark'
